import '@/assets/globals.css';
import { iranYekan } from '@/assets/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className={iranYekan.className}>
      <body>{children}</body>
    </html>
  );
}
